services:
    nginx:
        container_name: nginx
        image: nginx
        networks:
            - red_interna
            - red_monitor
        volumes:
            - ./html:/usr/share/nginx/html
        restart: always
        labels:
            caddy: "nginx.pruebafcthugocastelar.duckdns.org"
            caddy.reverse_proxy: "{{upstreams 80}}"

networks:
    red_interna:
        external: true
    red_monitor:
        external: true