services:
    mysql:
        container_name: mysql
        environment:
          - MYSQL_ROOT_PASSWORD=pruebafct
        image: mysql:latest
        networks:
          - red_interna
          - red_monitor
#        ports:
#          - "3306:3306"
        restart: always

networks:
    red_interna:
        external: true
    red_monitor:
        external: true