services:
  tomcat:
    container_name: tomcat
    image: tomcat:11.0.0
    volumes: 
      - ./webapps:/usr/local/tomcat/webapps
    networks:
      - red_interna
      - red_monitor
    restart: always
    labels:
      caddy: "tomcat.ut3hugocastelar.duckdns.org"
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
    red_interna:
        external: true
    red_monitor:
        external: true